services:
  web:
    build: .
    environment:
      NODE_ENV: production
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: daeGh@id379@@
      POSTGRES_DB: sleevetrack
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: sleevetrack
      POSTGRES_PASSWORD: daeGh@id379@@
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5